-- grade Data --
\connect classdb

DELETE FROM classes;
INSERT INTO classes (type, grade_id, name, created_at, updated_at) VALUES 
(1, 1, 'k1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 1, 'a1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 1, 't1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 1, 'o1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 2, 'l2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 2, 'j2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 2, 'o2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 3, 'm3', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 3, 'p3', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 3, 'q3', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);