-- grade Data --
\connect classdb

DELETE FROM classes;
DELETE FROM grade;

INSERT INTO classes (type, classes_id, grade_id, name, created_at, updated_at) VALUES 
(1, 1, 1, '一班', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 2, 1, '二班', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 3, 1, '三班', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 4, 2, '四班', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 5, 2, '五班', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 6, 2, '六班', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 7, 3, '七班', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 8, 3, '八班', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 9, 3, '九班', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 10, 3, '十班', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO grade (grade_id, name, created_at, updated_at) VALUES 
(1, '一年级', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '二年级', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, '三年级', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, '四年级', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, '五年级', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, '六年级', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);