services:
  account-service:
    container_name: account-service
    build:
      context: ./Services/AccountService
      dockerfile: Dockerfile
    ports:
      - 3010:3010
    depends_on:
      - postgres
    networks:
      - backend

  student-service:
    container_name: student-service
    build:
      context: ./Services/StudentService
      dockerfile: Dockerfile
    ports:
      - 3011:3011
    depends_on:
      - postgres
      - account-service
    networks:
      - backend

  studentapp:
    container_name: studentapp
    build:
      context: ./Apps/StudentApp
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - account-service
    networks:
      - frontend

  postgres:
    container_name: databases
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./sql/databases.sql:/docker-entrypoint-initdb.d/1.databases.sql
      - ./Services/AccountService/sql/databases.sql:/docker-entrypoint-initdb.d/2.databases.sql
      - ./Services/AccountService/sql/schema.sql:/docker-entrypoint-initdb.d/3.schema.sql
      - ./Services/AccountService/sql/data.sql:/docker-entrypoint-initdb.d/4.data.sql
      - ./Services/StudentService/sql/databases.sql:/docker-entrypoint-initdb.d/5.databases.sql
      - ./Services/StudentService/sql/schema.sql:/docker-entrypoint-initdb.d/6.schema.sql
      - ./Services/StudentService/sql/data.sql:/docker-entrypoint-initdb.d/7.data.sql
    networks:
      - backend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
