services:
  account-service:
    container_name: account-service
    build:
      context: ./Services/AccountService
      dockerfile: Dockerfile
    ports:
      - 3010:3010
    depends_on:
      - postgres
    networks:
      - backend

  student-service:
    container_name: student-service
    build:
      context: ./Services/StudentService
      dockerfile: Dockerfile
    ports:
      - 3011:3011
    depends_on:
      - postgres
      - account-service
    networks:
      - backend

  class-service:
    container_name: class-service
    build:
      context: ./Services/ClassService
      dockerfile: Dockerfile
    ports:
      - 3013:3013
    depends_on:
      - postgres
      - account-service
    networks:
      - backend

  studentapp:
    container_name: studentapp
    build:
      context: ./Apps/StudentApp
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - account-service
    networks:
      - frontend

  postgres:
    container_name: databases
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./sql/databases.sql:/docker-entrypoint-initdb.d/01.databases.sql
      - ./Services/AccountService/sql/databases.sql:/docker-entrypoint-initdb.d/02.databases.sql
      - ./Services/AccountService/sql/schema.sql:/docker-entrypoint-initdb.d/03.schema.sql
      - ./Services/AccountService/sql/data.sql:/docker-entrypoint-initdb.d/04.data.sql
      - ./Services/StudentService/sql/databases.sql:/docker-entrypoint-initdb.d/05.databases.sql
      - ./Services/StudentService/sql/schema.sql:/docker-entrypoint-initdb.d/06.schema.sql
      - ./Services/StudentService/sql/data.sql:/docker-entrypoint-initdb.d/07.data.sql
      - ./Services/ClassService/sql/databases.sql:/docker-entrypoint-initdb.d/08.databases.sql
      - ./Services/ClassService/sql/schema.sql:/docker-entrypoint-initdb.d/09.schema.sql
      - ./Services/ClassService/sql/data.sql:/docker-entrypoint-initdb.d/10.data.sql
    networks:
      - backend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
